### ISSUE TITLE
Waiting for pacemaker, pacemaker status not available

### ISSUE THREAD

**Issue by Manicknux** [rasto/lcmc#35]
Software setup:

Cman 6.2.0
Pacemaker 1.1.8

The setup worked find until I tried recreating the cluster using "eth1" instead of "eth0" for cluster communication.

Management is still performed through eth0, but upon connecting, LCMC cannot seem to see the running status of pacemaker.  Interestingly enough, if pacemaker is shutdown, LCMC sees this (shows as pcmk stopped), but when pacemaker reloads...it ends up with "wait" and will not allow for configuration.

crm_mon as well as pcs status shows that the cluster is fine and running correctly on the second interface.

Is there a step I'm missing in the normal setup of things?

And...rasto, thank you for this software, it's been a blessing...I just hope I can get it to work in this situation.

**Comment by mackot** [comment]
in newest (centos8) same problem but solution is simple: "same short-hostname" from hosts to corosync, just everywhere where is possible...
