### ISSUE TITLE
How to load the other lcmc-conf.lcmc?

### ISSUE THREAD

**Issue by ikedaj** [rasto/lcmc#42]
version: LCMC-1.7.3.jar

I am trying to open the configured lcmc-conf.lcmc in the menu bar.
[menu bar]->[session]->[new/open/load/save/save as]

"load" menu is grayed out despite the admin mode.
It seems that it needs "Application.OpMode.GOD", how can I switch the mode from admin to god?

**Comment by rasto** [comment]
I am not planning to include this feature at this moment
