### ISSUE TITLE
Intermittant high CPU load

### ISSUE THREAD

**Issue by sammcj** [rasto/lcmc#45]
I'm intermittently seeing incredibly high CPU usage from LCMC.
When it happens it maxes out one CPU core at 100% until the application is closed and reopened.

* Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
* Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
* OSX 10.10.3

I've uploaded a sample of the process while it was doing this here: https://gist.githubusercontent.com/sammcj/e290b7a29ac6a186aee9/raw/54a36f431c53849e4a8baff5d95e21de1e05a9cc/Sample%20of%20LCMC

**Comment by rasto** [comment]
I've seen some performance issues with openjdk recently. Use oracle java, please.
