### ISSUE TITLE
Support for Debian Jessie

### ISSUE THREAD

**Issue by tbnobody** [rasto/lcmc#49]
Tried to get LCMC working with Debian Jessie (install manual: https://wiki.debian.org/Debian-HA/ClustersFromScratch)

The Cluster wizard is unable to find the installed pacemaker. Found the issue in the method "get_crmd_lib_path" in the "lcmc-gui-helper" file.

In Jessie the crmd executable is located here:
/usr/lib/x86_64-linux-gnu/pacemaker/

**Comment by tbnobody** [comment]
The same path has to be added in the script "lcmc-gui-helper" in line 1051:

**Comment by rasto** [comment]
ok, thanks. Will be fixed in the next release 1.7.9
