### ISSUE TITLE
Windows 10: This application requires a Java Runtime Environment 1.10.0

### ISSUE THREAD

**Issue by solarmon** [rasto/lcmc#69]
Hi,

I'm trying to use **LCMC-1.7.17-windows.exe** on a **Windows 10** environment. When I launch it I get the following message:

![image](https://user-images.githubusercontent.com/46369787/94912354-72f67e00-049f-11eb-8e31-19653c581526.png)

If I close the window it opens up my browser to:

https://java.com/en/download/

and when I download **jre-8u261-windows-x64.exe** and install it and reboot:

![image](https://user-images.githubusercontent.com/46369787/94912646-e00a1380-049f-11eb-9feb-5b3b2e22b045.png)

However, still get the same error message when launching LCMC-1.7.17-windows.exe.

How do I get "Java Runtime Environment 1.10.0" installed to get this working?

Thank you.

**Comment by rasto** [comment]
You need Java 11, Java 8 won't do it.
